"""Deterministic design-plan QA (Task 9).

Pure rules — no LLM, no network, no clock, no randomness. ``evaluate_design_plan``
hard-gates a ``CarouselDesignPlan`` against its source atoms / direction /
asset manifest / family profile and returns a ``DesignPlanQAResult`` with
actionable, deterministically-ordered issues. The reviser loop (Task 8) and the
route defined here consume the result; graph wiring is Task 14.

Rule prefixes are ``content.`` / ``family.`` / ``asset.`` / ``geometry.`` /
``typography.``; the three attestations key off ``content.`` / ``family.`` /
``asset.``.
"""

from __future__ import annotations

import math
from collections.abc import Iterable
from dataclasses import dataclass

from src.schemas.assets import AssetManifest
from src.schemas.content_atoms import ContentAtomSet, canonical_sha256
from src.schemas.design_qa import DesignIssue, DesignPlanQAResult
from src.schemas.scene_graph import (
    Box,
    CarouselDesignPlan,
    IconElement,
    ImageElement,
    LineElement,
    PageScene,
    ShapeElement,
    TextElement,
)
from src.schemas.visual_director import VisualDirectionPlan
from src.schemas.visual_style import FamilyStyleProfile

# --- thresholds (brief Step 3, verbatim) ----------------------------------

MIN_BODY_FONT_PX = 24
MIN_DISPLAY_FONT_PX = 32
SAFE_MARGIN_PX = 84
NORMAL_TEXT_CONTRAST = 4.5
LARGE_TEXT_CONTRAST = 3.0

CANVAS_WIDTH = 1080
CANVAS_HEIGHT = 1440
_EPS = 1e-9

# Sentinel location for plan-level issues (DesignIssue requires a location).
_PLAN_LEVEL = "__plan__"

# Forbidden visible label / AI-source-disclosure / disclaimer phrases. Matched
# case-insensitively as substrings against the rendered atom text. This enforces
# the global "NEVER render compliance/disclaimer/AI-source text" rule. Public so
# ``render_qa`` (and any future defense-in-depth consumer) can re-use the same
# patterns without coupling to a private symbol.
FORBIDDEN_LABEL_PATTERNS = (
    "免责声明",
    "disclaimer",
    "ai生成",
    "ai-generated",
    "ai generated",
    "generated by ai",
    "由ai生成",
    "图片来源于网络",
    "图片来自网络",
    "侵删",
    "版权声明",
    "ai source",
    "ai披露",
    "来源:ai",
    "来源：ai",
)

# Markup / script-like markers that must never appear in rendered atom text.
_SCRIPT_LIKE_PATTERNS = (
    "<script",
    "<style",
    "<img",
    "<div",
    "<span",
    "<p>",
    "</",
    "javascript:",
    "<br",
    "<a ",
    "<iframe",
    "<svg",
    "style=",
)


# --- inputs ---------------------------------------------------------------

@dataclass(frozen=True)
class DesignPlanQAInputs:
    atoms: ContentAtomSet
    direction: VisualDirectionPlan
    assets: AssetManifest
    design_plan: CarouselDesignPlan
    style: FamilyStyleProfile


# --- WCAG color math ------------------------------------------------------

def _parse_hex(color: str) -> tuple[float, float, float]:
    r = int(color[1:3], 16)
    g = int(color[3:5], 16)
    b = int(color[5:7], 16)
    return float(r), float(g), float(b)


def _linearize(channel: float) -> float:
    normalized = channel / 255.0
    if normalized <= 0.03928:
        return normalized / 12.92
    return ((normalized + 0.055) / 1.055) ** 2.4


def _relative_luminance(color: str) -> float:
    r, g, b = _parse_hex(color)
    return (
        0.2126 * _linearize(r)
        + 0.7152 * _linearize(g)
        + 0.0722 * _linearize(b)
    )


def contrast_ratio(foreground: str, background: str) -> float:
    """WCAG contrast ratio between two ``#RRGGBB`` colors (1.0..21.0)."""
    fg = _relative_luminance(foreground)
    bg = _relative_luminance(background)
    lighter, darker = max(fg, bg), min(fg, bg)
    return (lighter + 0.05) / (darker + 0.05)


# --- geometry helpers -----------------------------------------------------

def _box_right(box: Box) -> float:
    return box.x + box.width


def _box_bottom(box: Box) -> float:
    return box.y + box.height


def _boxes_intersect(a: Box, b: Box) -> bool:
    # Touching edges (<=) do not count as an overlap.
    return not (
        _box_right(a) <= b.x + _EPS
        or _box_right(b) <= a.x + _EPS
        or _box_bottom(a) <= b.y + _EPS
        or _box_bottom(b) <= a.y + _EPS
    )


def _box_bearing_elements(page: PageScene) -> tuple:
    return tuple(
        element
        for element in page.elements
        if isinstance(element, (TextElement, ImageElement, ShapeElement, IconElement))
    )


# --- issue factory --------------------------------------------------------

def _issue(
    rule: str,
    message: str,
    repair_instruction: str,
    *,
    page_id: str | None = None,
    element_id: str | None = None,
    atom_id: str | None = None,
) -> DesignIssue:
    return DesignIssue(
        rule=rule,
        message=message,
        repair_instruction=repair_instruction,
        page_id=page_id,
        element_id=element_id,
        atom_id=atom_id,
    )


# --- hash bindings --------------------------------------------------------

def validate_hash_bindings(inputs: DesignPlanQAInputs) -> list[DesignIssue]:
    issues: list[DesignIssue] = []
    plan = inputs.design_plan
    if plan.direction_plan_sha256 != canonical_sha256(inputs.direction):
        issues.append(
            _issue(
                "family.direction_hash_mismatch",
                "design plan direction_plan_sha256 does not match the source direction plan",
                "regenerate the plan against the current VisualDirectionPlan",
                page_id=_PLAN_LEVEL,
            )
        )
    if plan.content_atom_set_sha256 != inputs.atoms.canonical_sha256:
        issues.append(
            _issue(
                "content.hash_mismatch",
                "design plan content_atom_set_sha256 does not match the source atom set",
                "rebind the plan to the current ContentAtomSet",
                page_id=_PLAN_LEVEL,
            )
        )
    if plan.asset_manifest_sha256 != canonical_sha256(inputs.assets):
        issues.append(
            _issue(
                "asset.hash_mismatch",
                "design plan asset_manifest_sha256 does not match the source manifest",
                "rebind the plan to the current AssetManifest",
                page_id=_PLAN_LEVEL,
            )
        )
    return issues


# --- content coverage -----------------------------------------------------

def validate_content_coverage(inputs: DesignPlanQAInputs) -> list[DesignIssue]:
    issues: list[DesignIssue] = []
    fragments = inputs.direction.content_fragments
    fragment_by_id = {fragment.fragment_id: fragment for fragment in fragments}
    order_index = {fragment.fragment_id: index for index, fragment in enumerate(fragments)}
    # Every fragment is owned by exactly one page (validated on the direction
    # plan). Naming that page on a missing-fragment issue lets the design
    # reviser know which page it is allowed to patch to add the text element;
    # without a page the reviser's "only named pages may change" rule forbids
    # touching any page and the required fix is impossible.
    fragment_owner_page = {
        fragment_id: page.page_id
        for page in inputs.direction.page_sequence
        for fragment_id in page.fragment_ids
    }

    rendered_count: dict[str, int] = {}

    for page in inputs.design_plan.pages:
        seen_on_page: set[str] = set()
        ordered_indices: list[int] = []
        for element in page.elements:
            if not isinstance(element, TextElement):
                continue
            ref = element.content_ref
            if ref not in fragment_by_id:
                issues.append(
                    _issue(
                        "content.unknown_content_ref",
                        f"text element references unknown content fragment {ref}",
                        f"point content_ref at a fragment owned by page {page.page_id}",
                        page_id=page.page_id,
                        element_id=element.element_id,
                    )
                )
                continue
            rendered_count[ref] = rendered_count.get(ref, 0) + 1
            if rendered_count[ref] > 1:
                issues.append(
                    _issue(
                        "content.duplicated_content_ref",
                        f"content fragment {ref} is rendered more than once",
                        f"render fragment {ref} exactly once in the plan",
                        page_id=page.page_id,
                        element_id=element.element_id,
                        atom_id=fragment_by_id[ref].source_atom_id,
                    )
                )
            if ref in seen_on_page:
                continue
            seen_on_page.add(ref)
            ordered_indices.append(order_index[ref])

        for earlier, later in zip(ordered_indices, ordered_indices[1:]):
            if later <= earlier:
                issues.append(
                    _issue(
                        "content.reordered_content_ref",
                        f"text fragments on page {page.page_id} are not in direction order",
                        "render the page's fragments in their source sequence",
                        page_id=page.page_id,
                    )
                )
                break

    for fragment in fragments:
        if rendered_count.get(fragment.fragment_id, 0) == 0:
            owner_page = fragment_owner_page.get(fragment.fragment_id)
            if owner_page is None:
                issues.append(
                    _issue(
                        "content.missing_fragment",
                        f"content fragment {fragment.fragment_id} is not rendered",
                        f"add a text element for fragment {fragment.fragment_id}",
                        atom_id=fragment.source_atom_id,
                    )
                )
                continue
            issues.append(
                _issue(
                    "content.missing_fragment",
                    f"content fragment {fragment.fragment_id} is not rendered "
                    f"on its owning page {owner_page}",
                    f"add a text element for fragment {fragment.fragment_id} "
                    f"on page {owner_page}",
                    page_id=owner_page,
                    atom_id=fragment.source_atom_id,
                )
            )
    return issues


# --- asset bindings -------------------------------------------------------

def validate_asset_bindings(inputs: DesignPlanQAInputs) -> list[DesignIssue]:
    issues: list[DesignIssue] = []
    asset_by_id = {item.asset_id: item for item in inputs.assets.items}
    directive_by_id = {
        directive.directive_id: directive
        for directive in inputs.direction.asset_directives
    }
    directive_owner_page = {
        directive_id: page.page_id
        for page in inputs.direction.page_sequence
        for directive_id in page.asset_directive_ids
    }

    rendered_assets: set[str] = set()
    for page in inputs.design_plan.pages:
        for element in page.elements:
            if not isinstance(element, ImageElement):
                continue
            asset = asset_by_id.get(element.asset_ref)
            if asset is None:
                issues.append(
                    _issue(
                        "asset.unknown_asset_ref",
                        f"image element references asset {element.asset_ref} not in the manifest",
                        "point asset_ref at an approved manifest asset",
                        page_id=page.page_id,
                        element_id=element.element_id,
                    )
                )
                continue
            rendered_assets.add(asset.asset_id)
            if asset.security_status != "approved":
                issues.append(
                    _issue(
                        "asset.unapproved_asset",
                        f"asset {asset.asset_id} is not security-approved",
                        "use an approved asset or drop the image element",
                        page_id=page.page_id,
                        element_id=element.element_id,
                    )
                )
            if asset.page_id != page.page_id:
                issues.append(
                    _issue(
                        "asset.wrong_page_asset",
                        f"asset {asset.asset_id} is bound to page {asset.page_id}, not {page.page_id}",
                        "use an asset approved for this page",
                        page_id=page.page_id,
                        element_id=element.element_id,
                    )
                )
            directive = directive_by_id.get(asset.directive_id)
            owner = directive_owner_page.get(asset.directive_id)
            if (
                directive is None
                or owner != page.page_id
                or directive.page_id != page.page_id
            ):
                issues.append(
                    _issue(
                        "asset.directive_not_owned",
                        f"asset {asset.asset_id} directive {asset.directive_id} is not owned by page {page.page_id}",
                        "bind the image to an asset whose directive targets this page",
                        page_id=page.page_id,
                        element_id=element.element_id,
                    )
                )

    for asset in inputs.assets.items:
        if asset.security_status == "approved" and asset.asset_id not in rendered_assets:
            issues.append(
                _issue(
                    "asset.unrendered_asset",
                    f"approved asset {asset.asset_id} is not rendered on page {asset.page_id}",
                    "add an image element that renders the approved asset",
                    page_id=asset.page_id,
                )
            )
    return issues


# --- geometry -------------------------------------------------------------

def _estimate_text_overflow(
    text: str,
    font_size: float,
    line_height: float,
    box: Box,
) -> bool:
    """Rough static overflow estimate for text in a box.

    CJK/full-width glyphs are roughly one ``font_size`` em wide each; latin,
    space, and punctuation glyphs are narrower (~0.55em). Sum the estimated
    text width, wrap it across the box width, and flag when the wrapped line
    height exceeds the box height. The estimate is deliberately approximate so
    borderline designs are not false-flagged; it exists to catch clearly
    impossible layouts (e.g. a full sentence set in 72px display type inside a
    narrow badge) before they reach the renderer.
    """
    if font_size <= 0 or line_height <= 0:
        return False
    total_ems = sum(
        1.0 if ord(char) > 0x2E80 else 0.55
        for char in text
    )
    total_width = total_ems * font_size
    lines = max(1, math.ceil(total_width / box.width))
    text_height = lines * font_size * line_height
    # Tolerance for rounding, descenders, and line-box padding.
    return text_height > box.height + 8.0


def validate_geometry(inputs: DesignPlanQAInputs) -> list[DesignIssue]:
    issues: list[DesignIssue] = []
    fragment_by_id = {
        fragment.fragment_id: fragment
        for fragment in inputs.direction.content_fragments
    }
    for page in inputs.design_plan.pages:
        bearing = _box_bearing_elements(page)
        for element in bearing:
            box = element.box
            if (
                _box_right(box) > CANVAS_WIDTH + _EPS
                or _box_bottom(box) > CANVAS_HEIGHT + _EPS
            ):
                issues.append(
                    _issue(
                        "geometry.box_out_of_bounds",
                        (
                            f"element box ({box.x},{box.y},{box.width},{box.height}) "
                            f"exceeds the {CANVAS_WIDTH}x{CANVAS_HEIGHT} canvas"
                        ),
                        "fit the element box inside the canvas",
                        page_id=page.page_id,
                        element_id=element.element_id,
                    )
                )
            if isinstance(element, (TextElement, IconElement)):
                if (
                    box.x < SAFE_MARGIN_PX - _EPS
                    or box.y < SAFE_MARGIN_PX - _EPS
                    or _box_right(box) > (CANVAS_WIDTH - SAFE_MARGIN_PX) + _EPS
                    or _box_bottom(box) > (CANVAS_HEIGHT - SAFE_MARGIN_PX) + _EPS
                ):
                    issues.append(
                        _issue(
                            "geometry.safe_margin_violation",
                            (
                                f"element enters the {SAFE_MARGIN_PX}px safe-margin exclusion "
                                f"on page {page.page_id}"
                            ),
                            f"keep readable content inside the {SAFE_MARGIN_PX}px safe area",
                            page_id=page.page_id,
                            element_id=element.element_id,
                        )
                    )
            if isinstance(element, TextElement):
                fragment = fragment_by_id.get(element.content_ref)
                if fragment is not None and _estimate_text_overflow(
                    fragment.text,
                    element.style.font_size,
                    element.style.line_height,
                    element.box,
                ):
                    issues.append(
                        _issue(
                            "geometry.text_overflow_estimate",
                            (
                                f"text element {element.element_id} likely overflows its "
                                f"box: {len(fragment.text)} characters at "
                                f"{element.style.font_size}px in a "
                                f"{int(box.width)}x{int(box.height)} box"
                            ),
                            (
                                f"reduce font_size or widen the box so the text fits "
                                f"({len(fragment.text)} characters)"
                            ),
                            page_id=page.page_id,
                            element_id=element.element_id,
                        )
                    )
        for i, first in enumerate(bearing):
            for second in bearing[i + 1:]:
                if not _boxes_intersect(first.box, second.box):
                    continue
                if second.element_id in first.intentional_overlap_with:
                    continue
                if first.element_id in second.intentional_overlap_with:
                    continue
                issues.append(
                    _issue(
                        "geometry.unintended_overlap",
                        (
                            f"elements {first.element_id} and {second.element_id} overlap "
                            f"on page {page.page_id} without intentional_overlap_with"
                        ),
                        "declare intentional_overlap_with or separate the elements",
                        page_id=page.page_id,
                        element_id=second.element_id,
                    )
                )
    return issues


# --- typography -----------------------------------------------------------

def _effective_text_background(page: PageScene, text: TextElement) -> str:
    """The background a viewer actually sees behind ``text``.

    Text often sits on a shape/card element over the page background (e.g.
    light text on a dark header bar). Comparing the text color to the page
    background in that case is a false contrast failure, so pick the topmost
    shape painted *behind* the text (lower layer, overlapping box) and use
    its fill; fall back to the page background when nothing sits behind it.
    """
    behind = [
        shape
        for shape in page.elements
        if isinstance(shape, ShapeElement)
        and shape.layer < text.layer
        and _boxes_intersect(shape.box, text.box)
    ]
    if not behind:
        return page.background
    return max(behind, key=lambda shape: shape.layer).fill


def validate_typography(inputs: DesignPlanQAInputs) -> list[DesignIssue]:
    issues: list[DesignIssue] = []
    for page in inputs.design_plan.pages:
        for element in page.elements:
            if not isinstance(element, TextElement):
                continue
            style = element.style
            background = _effective_text_background(page, element)
            role = style.font_role
            if role in ("body", "caption") and style.font_size < MIN_BODY_FONT_PX - _EPS:
                issues.append(
                    _issue(
                        "typography.undersized_body_text",
                        (
                            f"body/caption text size {style.font_size}px is below "
                            f"{MIN_BODY_FONT_PX}px"
                        ),
                        f"raise font_size to at least {MIN_BODY_FONT_PX}px",
                        page_id=page.page_id,
                        element_id=element.element_id,
                    )
                )
            if role in ("display", "heading") and style.font_size < MIN_DISPLAY_FONT_PX - _EPS:
                issues.append(
                    _issue(
                        "typography.undersized_display_text",
                        (
                            f"display/heading text size {style.font_size}px is below "
                            f"{MIN_DISPLAY_FONT_PX}px"
                        ),
                        f"raise font_size to at least {MIN_DISPLAY_FONT_PX}px",
                        page_id=page.page_id,
                        element_id=element.element_id,
                    )
                )
            is_large = style.font_size >= MIN_DISPLAY_FONT_PX - _EPS
            threshold = LARGE_TEXT_CONTRAST if is_large else NORMAL_TEXT_CONTRAST
            ratio = contrast_ratio(style.color, background)
            if ratio < threshold - _EPS:
                classification = "large" if is_large else "normal"
                issues.append(
                    _issue(
                        "typography.insufficient_contrast",
                        (
                            f"contrast ratio {ratio:.2f}:1 between text and background is "
                            f"below {threshold}:1 for {classification} text"
                        ),
                        "choose a text/background pair that meets the WCAG threshold",
                        page_id=page.page_id,
                        element_id=element.element_id,
                    )
                )
    return issues


# --- family envelope ------------------------------------------------------

def validate_family_envelope(inputs: DesignPlanQAInputs) -> list[DesignIssue]:
    issues: list[DesignIssue] = []
    style = inputs.style
    direction = inputs.direction
    plan = inputs.design_plan

    if style.family != direction.template_family:
        issues.append(
            _issue(
                "family.mismatch",
                f"style profile family {style.family} does not match direction family "
                f"{direction.template_family}",
                "load the family profile that matches the direction's template_family",
                page_id=_PLAN_LEVEL,
            )
        )

    page_count = len(plan.pages)
    if page_count < 5 or page_count > 18:
        issues.append(
            _issue(
                "family.page_count_out_of_range",
                f"design plan has {page_count} pages; allowed range is 5..18",
                "replan through visual_director for a valid page count",
                page_id=_PLAN_LEVEL,
            )
        )

    fragment_by_id = {fragment.fragment_id: fragment for fragment in direction.content_fragments}
    atom_by_id = {atom.atom_id: atom for atom in inputs.atoms.atoms}
    for page in plan.pages:
        for element in page.elements:
            if not isinstance(element, TextElement):
                continue
            fragment = fragment_by_id.get(element.content_ref)
            if fragment is None:
                continue
            atom = atom_by_id.get(fragment.source_atom_id)
            if atom is None:
                continue
            lowered = atom.text.lower()
            if any(pattern in lowered for pattern in FORBIDDEN_LABEL_PATTERNS):
                issues.append(
                    _issue(
                        "family.forbidden_visible_label",
                        f"atom {atom.atom_id} renders a forbidden visible label/disclaimer/AI disclosure",
                        "remove the disclaimer/AI-disclosure text from the content atom",
                        page_id=page.page_id,
                        element_id=element.element_id,
                        atom_id=atom.atom_id,
                    )
                )
            if any(pattern in lowered for pattern in _SCRIPT_LIKE_PATTERNS):
                issues.append(
                    _issue(
                        "family.script_like_content",
                        f"atom {atom.atom_id} contains HTML/CSS/script-like markup",
                        "strip markup from the content atom text",
                        page_id=page.page_id,
                        element_id=element.element_id,
                        atom_id=atom.atom_id,
                    )
                )
    return issues


# --- composition ----------------------------------------------------------

def evaluate_design_plan(inputs: DesignPlanQAInputs) -> DesignPlanQAResult:
    """Run every deterministic rule and return a hard-gate QA result.

    Issue order is stable: hash -> content -> asset -> geometry -> typography ->
    family, and within each validator issues are emitted in a deterministic
    page-sequence / element-order walk. Same inputs always yield the same issue
    tuple in the same order.
    """
    issues: Iterable[DesignIssue] = (
        validate_hash_bindings(inputs)
        + validate_content_coverage(inputs)
        + validate_asset_bindings(inputs)
        + validate_geometry(inputs)
        + validate_typography(inputs)
        + validate_family_envelope(inputs)
    )
    issue_tuple = tuple(issues)

    return DesignPlanQAResult(
        passed=not issue_tuple,
        issues=issue_tuple,
        design_plan_sha256=canonical_sha256(inputs.design_plan),
        content_coverage_attestation=not any(
            issue.rule.startswith("content.") for issue in issue_tuple
        ),
        family_attestation=not any(
            issue.rule.startswith("family.") for issue in issue_tuple
        ),
        asset_binding_attestation=not any(
            issue.rule.startswith("asset.") for issue in issue_tuple
        ),
    )


__all__ = [
    "CANVAS_HEIGHT",
    "CANVAS_WIDTH",
    "DesignPlanQAInputs",
    "FORBIDDEN_LABEL_PATTERNS",
    "LARGE_TEXT_CONTRAST",
    "MIN_BODY_FONT_PX",
    "MIN_DISPLAY_FONT_PX",
    "NORMAL_TEXT_CONTRAST",
    "SAFE_MARGIN_PX",
    "contrast_ratio",
    "evaluate_design_plan",
    "validate_asset_bindings",
    "validate_content_coverage",
    "validate_family_envelope",
    "validate_geometry",
    "validate_hash_bindings",
    "validate_typography",
]
